export const addCell = text => ({ type: 'ADD_CELL', text })
export const editCell = (text, id) => ({ type: 'EDIT_CELL', text, id })
export const editCellType = (id, cell_type, prev_text) => ({ type: 'EDIT_CELL_TYPE', id, cell_type, prev_text })
export const deleteCell = id => ({ type: 'DELETE_CELL', id })
export const addTodo = id => ({ type: 'ADD_TODO', id })
export const toggleTodo = (cellId, todoId) => ({ type: 'TOGGLE_TODO', cellId, todoId })
export const editTodo = (cellId, todoId, text) => ({ type: 'EDIT_TODO', cellId, todoId, text })
export const deleteTodo = (cellId, todoId) => ({ type: 'DELETE_TODO', cellId, todoId })